insert into articulo(articulo, costo)
    values("Malla de Hierro", 650),
          ("Malla de Acero", 1400),
          ("Soberanía", 2100),
          ("Malla mística", 2450),
          ("Cota de Midgard", 2300),
          ("Armadura del Emperador", 2250)
          ("Espada Ligera", 600),
          ("Cuchilla Balanceada", 1250),
          ("El Ejecutor", 2200),
          ("Sais de Quin", 2600),
          ("Asi", 2400),
          ("El Gran Ejecutor", 2200),
          ("El Ejecutor Feroz", 2200),
          ("Baratija Pequeña", 550),
          ("Baratija Encantada", 1100),
          ("Garra Baratija", 1400),
          ("Pieza de Pitágoras", 2300),
          ("Garra de Bancroft", 2500),
          ("Colmillo de Tifón", 2650),
          ("Gema de Alma", 2400),
          ("Mazo", 650),
          ("Perdición del Guerrero", 1500),
          ("Maza pesada", 1450),
          ("Perdición del Titán", 2500),
          ("Ira de Jotunn", 2200),
          ("El triturador", 2500),
          ("Garrote del buscapleitos", 2400),
          ("Vigor del Jotunn", 2150),
          ("Astucia de Jotunn", 2150),
          ("Lucero del Alba", 600),
          ("Lucero del Alba Cargado", 1200),
          ("Estrella de la Hydra", 1200),
          ("Trascendencia", 2500),
          ("Lamento de la Hydra", 2300),
          ("Buscacorazones", 2750),
          ("Dominación", 2500),
          ("Daga embrujada", 1900),
          ("Daga sobrenatural", 1900),
          ("Trascendencia evolucionada", 2501),
          ("Zarpa de Bancroft", 2550),
          ("Garra de Bancroft ágil", 2550),
          ("Daga oculta", 700),
          ("Espada Corte", 1350),
          ("Portador de la Muerte", 2900),
          ("Furia", 2500),
          ("Espada demoniaca", 2400),
          ("Bumerán afilado", 2350),
          ("Furia evolucionada", 1800),
          ("Portador de muerte malicioso", 2800),
          ("Portador de muerte envenenado", 2800),
          ("Guantelete con púas", 600),
          ("Guantelete maldito", 1400),
          ("Guantelete Ligado", 1050),
          ("Devoraalmas", 2100),
          ("Guantes del Devorador", 2400),
          ("Forja Sangrienta", 2600),
          ("Guantes del devorador evolucionados", 2401),
          ("Devora almas Evolucionado", 2100),
          ("Cuchilla Antigua", 550),
          ("Cuchilla del Aventurero", 1150),
          ("Hoja maldita", 1250),
          ("Daga Antigua", 1850),
          ("Cuchilla alada", 1850),
          ("Hoja tóxica", 2300),
          ("Hoz de loto", 2000),
          ("Garrote", 650),
          ("Martillo Pesado", 1350),
          ("Heraldo del amanecer", 2400),
          ("Martillo escarchado", 2250),
          ("Martillo de runa forjada", 2300),
          ("Martillo forjado con llamas", 2250),
          ("Martillo romperrunas", 2250),
          ("Escudo redondeado", 650),
          ("Escudo de Torre", 1150),
          ("Escudo de Berserker", 2300),
          ("Escudo del gladiador", 2350),
          ("Falange", 2200),
          ("Peto", 600),
          ("Peto Plateado", 1050),
          ("Peto de Valor", 2250),
          ("Contagio", 2250),
          ("Armadura espectral", 2300),
          ("Peto de renacimiento", 2250),
          ("Peto de determinación", 2250),
          ("Peto de vigilancia", 2250),
          ("Guantelete de Tebas Evolucionado", 1750),
          ("Capa", 600),
          ("Capa de Concentración", 1500),
          ("Capa del clérigo", 1150),
          ("Capa de los Magos", 2150),
          ("Túnica espiritual", 2400),
          ("Manto de la discordia", 2900),
          ("Capa profética", 2350),
          ("Cobijo de mago", 2150),
          ("Venganza del mago", 2150),
          ("Capa profética evolucionada", 2350),
          ("Talismán", 650),
          ("Talismán Plateado", 1250),
          ("Amuleto Guardacorazón", 2100),
          ("Talismán de Energia", 2150),
          ("Absolución", 2250),
          ("Pestilencia", 2400),
          ("Amuleto de silencio", 2050),
          ("Amuleto de la fortaleza", 2050),
          ("Anillo de Esmeralda", 600),
          ("Anillo Encantado", 1300),
          ("Agarre Demoniaco", 2300),
          ("Anillo de Telquines", 2250),
          ("Anillo Acelerado", 2600),
          ("Anillo ciclópeo", 2600),
          ("Concentración mágica", 650),
          ("Hechizo de Concentración", 1500),
          ("Lanza Encantada", 1400),
          ("Lanza de la Desolación", 2350),
          ("Fragmento obsidiano", 2500),
          ("Lanza de magus", 2450),
          ("Ruina divina", 2450),
          ("Bastón Poco Común", 650),
          ("Bastón del Brujo", 1350),
          ("Bastón fortificado", 1350),
          ("Joya de Aislamiento", 2550),
          ("Bastón de Hechicero", 2500),
          ("Bastón etéreo", 2600),
          ("Bastón del hechicero evolucionado", 2501),
          ("Libro de Hechizos", 650),
          ("Libro de Almas", 1350),
          ("Libro de Thoth", 2500),
          ("Polynomicón", 2300),
          ("Saqueador de Almas", 2650),
          ("Tabilla de destinos", 2550),
          ("Libro de Thoth Evolucionado", 2501),
          ("Artefacto Perdido", 550),
          ("Orbe de maldición", 1600),
          ("Artefacto Restaurado", 1400),
          ("Vara de Tahuti", 2850),
          ("Colgante de Cronos", 2600),
          ("Orbe de la perdición", 2850),
          ("Moneda de Caronte", 2400),
          ("Moneda de Caronte evolucionada", 2401),
          ("Vara de Tahuti calamitosa", 2900),
          ("Vara de Tahuti perfeccionada", 2900),
          ("Arco corto", 650),
          ("Arco Cargado", 1200),
          ("Arco del Cazador", 1200),
          ("Arco de Odiseo", 2100),
          ("")
