insert into articulo(articulo, costo)
    values("Malla de Hierro", 650),
          ("Malla de Acero", 1400),
          ("Soberanía", 2100),
          ("Malla mística", 2450),
          ("Cota de Midgard", 2300),
          ("Armadura del Emperador", 2250)
          ("Espada Ligera", 600),
          ("Cuchilla Balanceada", 1250),
          ("El Ejecutor", 2200),
          ("Sais de Quin", 2600),
          ("Asi", 2400),
          ("El Gran Ejecutor", 2200),
          ("El Ejecutor Feroz", 2200),
          ("Baratija Pequeña", 550),
          ("Baratija Encantada", 1100),
          ("Garra Baratija", 1400),
          ("Pieza de Pitágoras", 2300),
          ("Garra de Bancroft", 2500),
          ("Colmillo de Tifón", 2650),
          ("Gema de Alma", 2400),
          ("Mazo", 650),
          ("Perdición del Guerrero", 1500),
          ("Maza pesada", 1450),
          ("Perdición del Titán", 2500),
          ("Ira de Jotunn", 2200),
          ("El triturador", 2500),
          ("Garrote del buscapleitos", 2400),
          ("Vigor del Jotunn", 2150),
          ("Astucia de Jotunn", 2150),
          ("Lucero del Alba", 600),
          ("Lucero del Alba Cargado", 1200),
          ("Estrella de la Hydra", 1200),
          ("Trascendencia", 2500),
          ("Lamento de la Hydra", 2300),
          ("Buscacorazones", 2750),
          ("Dominación", 2500),
          ("Daga embrujada", 1900),
          ("Daga sobrenatural", 1900),
          ("Trascendencia evolucionada", 2501),
          ("Zarpa de Bancroft", 2550),
          ("Garra de Bancroft ágil", 2550),
          ("Daga oculta", 700),
          ("Espada Corte", 1350),
          ("Portador de la Muerte", 2900),
          ("Furia", 2500),
          ("Espada demoniaca", 2400),
          ("Bumerán afilado", 2350),
          ("Furia evolucionada", 1800),
          ("Portador de muerte malicioso", 2800),
          ("Portador de muerte envenenado", 2800),
          ("Guantelete con púas", 600),
          ("Guantelete maldito", 1400),
          ("Guantelete Ligado", 1050),
          ("Devoraalmas", 2100),
          ("Guantes del Devorador", 2400),
          ("Forja Sangrienta", 2600),
          ("Guantes del devorador evolucionados", 2401),
          ("Devora almas Evolucionado", 2100),
          ("Cuchilla Antigua", 550),
          ("Cuchilla del Aventurero", 1150),
          ("Hoja maldita", 1250),
          ("Daga Antigua", 1850),
          ("Cuchilla alada", 1850),
          ("Hoja tóxica", 2300),
          ("Hoz de loto", 2000),
          ("Garrote", 650),
          ("Martillo Pesado", 1350),
          ("Heraldo del amanecer", 2400),
          ("Martillo escarchado", 2250),
          ("Martillo de runa forjada", 2300),
          ("Martillo forjado con llamas", 2250),
          ("Martillo romperrunas", 2250),
          ("Escudo redondeado", 650),
          ("Escudo de Torre", 1150),
          ("Escudo de Berserker", 2300),
          ("Escudo del gladiador", 2350),
          ("Falange", 2200),
          ("Peto", 600),
          ("Peto Plateado", 1050),
          ("Peto de Valor", 2250),
          ("Contagio", 2250),
          ("Armadura espectral", 2300),
          ("Peto de renacimiento", 2250),
          ("Peto de determinación", 2250),
          ("Peto de vigilancia", 2250),
          ("Guantelete de Tebas Evolucionado", 1750),
          ("Capa", 600),
          ("Capa de Concentración", 1500),
          ("Capa del clérigo", 1150),
          ("Capa de los Magos", 2150),
          ("Túnica espiritual", 2400),
          ("Manto de la discordia", 2900),
          ("Capa profética", 2350),
          ("Cobijo de mago", 2150),
          ("Venganza del mago", 2150),
          ("Capa profética evolucionada", 2350),
          ("Talismán", 650),
          ("Talismán Plateado", 1250),
          ("Amuleto Guardacorazón", 2100),
          ("Talismán de Energia", 2150),
          ("Absolución", 2250),
          ("Pestilencia", 2400),
          ("Amuleto de silencio", 2050),
          ("Amuleto de la fortaleza", 2050),
          ("Anillo de Esmeralda", 600),
          ("Anillo Encantado", 1300),
          ("Agarre Demoniaco", 2300),
          ("Anillo de Telquines", 2250),
          ("Anillo Acelerado", 2600),
          ("Anillo ciclópeo", 2600),
          ("Concentración mágica", 650),
          ("Hechizo de Concentración", 1500),
          ("Lanza Encantada", 1400),
          ("Lanza de la Desolación", 2350),
          ("Fragmento obsidiano", 2500),
          ("Lanza de magus", 2450),
          ("Ruina divina", 2450),
          ("Bastón Poco Común", 650),
          ("Bastón del Brujo", 1350),
          ("Bastón fortificado", 1350),
          ("Joya de Aislamiento", 2550),
          ("Bastón de Hechicero", 2500),
          ("Bastón etéreo", 2600),
          ("Bastón del hechicero evolucionado", 2501),
          ("Libro de Hechizos", 650),
          ("Libro de Almas", 1350),
          ("Libro de Thoth", 2500),
          ("Polynomicón", 2300),
          ("Saqueador de Almas", 2650),
          ("Tabilla de destinos", 2550),
          ("Libro de Thoth Evolucionado", 2501),
          ("Artefacto Perdido", 550),
          ("Orbe de maldición", 1600),
          ("Artefacto Restaurado", 1400),
          ("Vara de Tahuti", 2850),
          ("Colgante de Cronos", 2600),
          ("Orbe de la perdición", 2850),
          ("Moneda de Caronte", 2400),
          ("Moneda de Caronte evolucionada", 2401),
          ("Vara de Tahuti calamitosa", 2900),
          ("Vara de Tahuti perfeccionada", 2900),
          ("Arco corto", 650),
          ("Arco Cargado", 1200),
          ("Arco del Cazador", 1200),
          ("Arco de Odiseo", 2100),
          ("Arco de rama plateada", 1350),
          ("Arco de Atalanta", 1100),
          ("Esmeralda resplandeciente", 600),
          ("Talisman de Esmeralda", 1400),
          ("Malla Esmeralda" 1250),
          ("Piedra de Gea", 2100),
          ("Guantelete de Tebas", 2350),
          ("Malla de la renovación", 2200),
          ("Coraza de cañonero", 2000),
          ("Katana", 600),
          ("Mil hojas dobladas", 1250),
          ("Katana acelerada", 2450),
          ("Espada de oro", 2150),
          ("Filo serrado", 2500),
          ("Bebedor de sombra", 2300),
          ("Kusari Encantado", 650),
          ("Kusari Hechizado", 1250),
          ("Guardia de Genji", 2200),
          ("Atuendo del Cazador Oni", 2100),
          ("Kusari de Shogun", 2200),
          ("Piedra Druida", 650),
          ("Piedra del Sabio", 1400),
          ("Piedra de la Unión", 2300),
          ("Furia del archidruida", 2300),
          ("Piedra abisal", 2350),
          ("Erosión", 2250),
          ("Máscara del Luchador", 650),
          ("Máscara de Rangda", 2150),
          ("Gema del destino", 900),
          ("Borde afilado", 1600),
          ("Escudo de caballero", 1600),
          ("Bastón del aprendiz", 1600),
          ("Pridwen", 2400),
          ("Arondight", 2600),
          ("Arco que no falla", 2650),
          ("Bastón de Merlín", 2600),
          ("Pridwen glorioso", 2100),
          ("Pridwen reverente", 2100),
          ("Bellota mágica", 0),
          ("Bellota vigorosa", 700),
          ("Bellota de ortiga", 700),
          ("Bellota erizada", 2050),
          ("Bellota espinosa", 2050),
          ("Bellota perenne", 2050),
          ("Bellota carnosa", 2050),
          ("Precio de la muerte", 650),
          ("Abrazo de la muerte", 2150),
          ("Temperamento de la muerte", 2150),
          ("Flecha dorada", 650),
          ("Flecha de diamante", 2150),
          ("Flecha adornada", 2150),
          ("Hacha del guerrero", 650),
          ("Hacha desgarradora", 2150),
          ("Hacha de animosidad", 2150),
          ("Cetro de maniquí", 650),
          ("Maza de maniquí", 2150),
          ("Espada oculta de maniquí", 2150),
          ("Daga de Bumba", 600),
          ("Lanza de Bumba", 2100),
          ("Martillo de Bumba", 2100),
          ("Arenas del tiempo", 700),
          ("Péndulo del tiempo", 2200),
          ("Línea cronológica alternativa", 2200),
          ("Manto vampírico", 650),
          ("Manto empapado de sangre", 2150),
          ("Manto de sacrificio", 2150),
          ("Regalo del centinela", 550),
          ("Bendición del centinela", 1800),
          ("Abrazo del centinela", 1800),
          ("Benevolencia", 600),
          ("Compasión", 1850),
          ("Heroísmo", 1850),
          ("Acero contaminado", 600),
          ("Amuleto contaminado", 2100),
          ("Peto contaminado", 2100),
          ("Capucha de cuero", 650),
          ("Capucha de cazador", 2150),
          ("Capucha de lider", 2150),
          ("Gema de conducto", 700),
          ("Gema de archimago", 2200),
          ("Gema de concentración", 2200),
          ("Ojo de la Jungla", 650),
          ("Vidente d ela Jungla", 2150),
          ("Protector de la Juntgla", 2150),
          ("Sello protector", 650),
          ("Sello de la vieja guardia", 2150),
          ("Sello infundido", 2150),
          ("Máscara del protector", 650),
          ("Máscara de Lono", 1900),
          ("Pendiente místico", 400),
          ("Pendientes relucientes", 1300),
          ("Pendientes de espina de rosa", 1200),
          ("Gemelos con joyas", 1400),
          ("Aros bendecidos por hadas", 2300),
          ("Adornos de esfinge", 2450),
          ("Pinchos de la mantícora", 2300),
          ("Pendientes de ala de grifo", 2200),
          ("Pendiente piedra azul", 650),
          ("Broche piedra azul", 2150),
          ("Piedra azul corrupta", 2150),
          ("Bandera de guerra", 600),
          ("Bandera espartana", 1850),
          ("Estandarte de guerra", 1850),
          ("Varita restaudadora", 650),
          ("Vara de Curación", 1350),
          ("Vara de Asclepius", 2600),
          ("Corazón rejuvenecedor", 2450),
          ("Último suspiro", 2400),
          ("Cetro bendito", 650),
          ("Cetro espléndido", 1300),
          ("Garrote caduceo", 2400),
          ("Amplificador vital", 2450),
          ("Cetro de Sekhmet", 2400),
          ("Grosellas grandiosas - Paso 1", 0),
          ("Grosellas grandiosas - Paso 2", 0),
          ("Grosellas grandiosas", 0),
          ("Estofado energético - Paso 1", 0),
          ("Estofado energético - Paso 2", 0),
          ("Estofado energético", 0),
          ("Bao buenísimo - Paso 1", 0),
          ("Bao buenísimo - Paso 2", 0),
          ("Bap buenísimo", 0),
          ("Vuelo magnífico - Paso 1", 0),
          ("Vuelo magnífico - Paso 2", 0),
          ("Vuelo magnífico", 0),
          ("Ponche potente - Paso 1", 0),
          ("Ponche potente - Paso 2", 0),
          ("Ponche potente", 0),
          ("Reliquia", 0),
          ("Amuleto Aegis", 0),
          ("Gran amuleto Aegis", 300),
          ("Égida de juicio", 800),
          ("Égida de aceleración", 800),
          ("Cinturón de frenesí", 0),
          ("Gran cinturón de frenesí", 300),
          ("Cinturón del frenético", 800),
          ("Cinturón del hambre insaciable", 800),
          ("Runa de pestañeo", 0),
          ("Gran runa de pestañeo", 300),
          ("Runa de pestañeo abrasador", 800),
          ("Runa de pestañeo corrupta", 800),
          ("Brazal de resplandor", 0),
          ("Gran brazal de resplandor", 300),
          ("Brazal de iluminación", 800),
          ("Brazal de brillo", 800),
          ("Ankh maldito", 0),
          ("Gran ankh maldito", 300),
          ("Ankh anemago", 800),
          ("Ankh maldito", 800),
          ("Alas celestiales", 0),
          ("Grandes alas celestiales", 300),
          ("Alas de enredadera", 800),
          ("Alas aceleradas", 800),
          ("Emblema horrorífico", 0),
          ("Gran emblema horrorífico", 300),
          ("Emblema de pelibro creciente", 800),
          ("Emblema de terror tembloroso", 800),
          ("Caparazón mágico", 0),
          ("Gran caparazón mágico", 300),
          ("Caparazón fortificado", 800),
          ("Caparazón fantasma", 800),
          ("Capa de meditación", 0),
          ("Gran capa de meditación", 300),
          ("Capa del avatar", 800),
          ("Capa del asceta", 800),
          ("Cuencas de purificación", 0),
          ("Grandes cuencas de purificación", 300),
          ("Cuencas caóticas", 800),
          ("Cuencas temporales", 800),
          ("Escudo de Espinas", 0),
          ("Gran escudo de espinas", 300),
          ("Espinas de sobrecrecimiento", 800),
          ("Espinas de fuerza agotadora", 800),
          ("Lanza desgarradora", 0),
          ("Gran lanza desgarradora", 300),
          ("Explosión desgarradora", 800),
          ("Sifón desgarrador", 800),
          ("Fragmento de teletransporte", 0),
          ("Gran fragmento teletransporte", 300),
          ("Teletransporte persistente", 800),
          ("Teletransporte heroico", 800),
          ("Reliquia de fragmento", 0),
          ("Fragmento de caparazón", 0),
          ("Fragmento de visión", 0),
          ("Fragmento de cuerno", 0),
          ("Fragmento de garra", 0),
          ("Fragmento de ala", 0),
          ("Posión curativa", 50),
          ("Posión de maná", 50),
          ("Centinela", 50),
          ("Elixir de poder", 3000),
          ("Elixir de defensa", 3000),
          ("Fuarda centinela", 120),
          ("Multi Poción", 50),
          ("Tácticas de Miedo", 0),
          ("Cáliz de curación", 300),
          ("Cáliz de maná", 300),
          ("Cáliz del Oráculo", 400),
          ("Poción del Barón", 150),
          ("Pócima de poder", 500),
          ("Bomba rúnica", 50);