insert into jugador_articulo(nombre, articulo)
values('Kevin Gonzalez', 'Malla de Hierro'),
('Damian Maldonado', 'Malla de Acero'),
('Martín Galeano', 'Soberanía'),
('Agustín Oliverio', 'Malla mística'),
('Ezequiel Fernandez', 'Cota de Midgard'),
('Nicolás Lopez', 'Armadura del Emperador'),
('Valentín Cañete', 'Espada Ligera'),
('Benjamín Castro Madrid', 'Cuchilla Balanceada'),
('Agustina Gonzalez', 'El Ejecutor'),
('Matheo Moro', 'Sais de Quin'),
('Kevin Gonzalez', 'Asi'),
('Agustín Oliverio', 'El Gran Ejecutor'),
('Valentín Cañete', 'El Ejecutor Feroz'),
('Martín Galeano', 'Baratija Pequeña'),
('Martín Galeano', 'Baratija Encantada'),
('Agustín Oliverio', 'Garra Baratija'),
('Agustín Oliverio', 'Pieza de Pitágoras'),
('Agustín Oliverio', 'Garra de Bancroft'),
('Martín Galeano', 'Colmillo de Tifón'),
('Damian Maldonado', 'Gema de Alma'),
('Martín Galeano', 'Mazo'),
('Agustín Oliverio', 'Perdición del Guerrero'),
('Benjamín Castro Madrid', 'Maza pesada'),
('Agustín Oliverio', 'Perdición del Titán'),
('Agustina Gonzalez', 'Ira de Jotunn'),
('Agustín Oliverio', 'El triturador'),
('Nicolás Lopez', 'Garrote del buscapleitos'),
('Agustín Oliverio', 'Vigor del Jotunn'),
('Valentín Cañete', 'Astucia de Jotunn'),
('Agustina Gonzalez', 'Lucero del Alba'),
('Martín Galeano', 'Lucero del Alba Cargado'),
('Agustín Oliverio', 'Estrella de la Hydra'),
('Matheo Moro', 'Trascendencia'),
('Agustina Gonzalez', 'Lamento de la Hydra'),
('Agustina Gonzalez', 'Buscacorazones'),
('Agustín Oliverio', 'Dominación'),
('Benjamín Castro Madrid', 'Daga embrujada'),
('Benjamín Castro Madrid', 'Daga sobrenatural'),
('Agustín Oliverio', 'Trascendencia evolucionada'),
('Agustina Gonzalez', 'Zarpa de Bancroft'),
('Agustín Oliverio', 'Garra de Bancroft ágil'),
('Agustín Oliverio', 'Daga oculta'),
('Matheo Moro', 'Espada Corte'),
('Benjamín Castro Madrid', 'Portador de la Muerte'),
('Matheo Moro', 'Furia'),
('Agustín Oliverio', 'Espada demoniaca'),
('Agustín Oliverio', 'Bumerán afilado'),
('Agustina Gonzalez', 'Furia evolucionada'),
('Agustina Gonzalez', 'Portador de muerte malicioso'),
('Matheo Moro', 'Portador de muerte envenenado'),
('Kevin Gonzalez', 'Guantelete con púas'),
('Nicolás Lopez', 'Guantelete maldito'),
('Agustina Gonzalez', 'Guantelete Ligado'),
('Agustina Gonzalez', 'Devoraalmas'),
('Agustina Gonzalez', 'Guantes del Devorador'),
('Ezequiel Fernandez', 'Forja Sangrienta'),
('Matheo Moro', 'Guantes del devorador evolucionados'),
('Agustina Gonzalez', 'Devora almas Evolucionado'),
('Agustín Oliverio', 'Cuchilla Antigua'),
('Ezequiel Fernandez', 'Cuchilla del Aventurero'),
('Matheo Moro', 'Hoja maldita'),
('Agustín Oliverio', 'Daga Antigua'),
('Agustín Oliverio', 'Cuchilla alada'),
('Agustín Oliverio', 'Hoja tóxica'),
('Damian Maldonado', 'Hoz de loto'),
('Agustín Oliverio', 'Garrote'),
('Agustín Oliverio', 'Martillo Pesado'),
('Kevin Gonzalez', 'Heraldo del amanecer'),
('Martín Galeano', 'Martillo escarchado'),
('Martín Galeano', 'Martillo de runa forjada'),
('Agustín Oliverio', 'Martillo forjado con llamas'),
('Nicolás Lopez', 'Martillo romperrunas'),
('Martín Galeano', 'Escudo redondeado'),
('Matheo Moro', 'Escudo de Torre'),
('Agustín Oliverio', 'Escudo de Berserker'),
('Agustina Gonzalez', 'Escudo del gladiador'),
('Ezequiel Fernandez', 'Falange'),
('Agustín Oliverio', 'Peto'),
('Matheo Moro', 'Peto Plateado'),
('Agustín Oliverio', 'Peto de Valor'),
('Matheo Moro', 'Contagio'),
('Benjamín Castro Madrid', 'Armadura espectral'),
('Agustín Oliverio', 'Peto de renacimiento'),
('Damian Maldonado', 'Peto de determinación'),
('Agustín Oliverio', 'Peto de vigilancia'),
('Agustín Oliverio', 'Guantelete de Tebas Evolucionado'),
('Benjamín Castro Madrid', 'Capa'),
('Agustín Oliverio', 'Capa de Concentración'),
('Agustina Gonzalez', 'Capa del clérigo'),
('Agustina Gonzalez', 'Capa de los Magos'),
('Agustina Gonzalez', 'Túnica espiritual'),
('Kevin Gonzalez', 'Manto de la discordia'),
('Valentín Cañete', 'Capa profética'),
('Agustín Oliverio', 'Cobijo de mago'),
('Agustina Gonzalez', 'Venganza del mago'),
('Agustina Gonzalez', 'Capa profética evolucionada'),
('Agustín Oliverio', 'Talismán'),
('Martín Galeano', 'Talismán Plateado'),
('Agustín Oliverio', 'Amuleto Guardacorazón'),
('Agustín Oliverio', 'Talismán de Energia'),
('Agustín Oliverio', 'Absolución'),
('Benjamín Castro Madrid', 'Pestilencia'),
('Martín Galeano', 'Amuleto de silencio'),
('Agustín Oliverio', 'Amuleto de la fortaleza'),
('Martín Galeano', 'Anillo de Esmeralda'),
('Kevin Gonzalez', 'Anillo Encantado'),
('Valentín Cañete', 'Agarre Demoniaco'),
('Agustín Oliverio', 'Anillo de Telquines'),
('Agustín Oliverio', 'Anillo Acelerado'),
('Ezequiel Fernandez', 'Anillo ciclópeo'),
('Martín Galeano', 'Concentración mágica'),
('Agustín Oliverio', 'Hechizo de Concentración'),
('Matheo Moro', 'Lanza Encantada'),
('Agustín Oliverio', 'Lanza de la Desolación'),
('Martín Galeano', 'Fragmento obsidiano'),
('Martín Galeano', 'Lanza de magus'),
('Agustín Oliverio', 'Ruina divina'),
('Matheo Moro', 'Bastón Poco Común'),
('Matheo Moro', 'Bastón del Brujo'),
('Agustín Oliverio', 'Bastón fortificado'),
('Agustín Oliverio', 'Joya de Aislamiento'),
('Agustín Oliverio', 'Bastón de Hechicero'),
('Agustín Oliverio', 'Bastón etéreo'),
('Agustín Oliverio', 'Bastón del hechicero evolucionado'),
('Agustín Oliverio', 'Libro de Hechizos'),
('Benjamín Castro Madrid', 'Libro de Almas'),
('Martín Galeano', 'Libro de Thoth'),
('Agustín Oliverio', 'Polynomicón'),
('Agustín Oliverio', 'Saqueador de Almas'),
('Agustina Gonzalez', 'Tabilla de destinos'),
('Agustín Oliverio', 'Libro de Thoth Evolucionado'),
('Matheo Moro', 'Artefacto Perdido'),
('Matheo Moro', 'Orbe de maldición'),
('Agustín Oliverio', 'Artefacto Restaurado'),
('Agustín Oliverio', 'Vara de Tahuti'),
('Damian Maldonado', 'Colgante de Cronos'),
('Agustín Oliverio', 'Orbe de la perdición'),
('Nicolás Lopez', 'Moneda de Caronte'),
('Damian Maldonado', 'Moneda de Caronte evolucionada'),
('Nicolás Lopez', 'Vara de Tahuti calamitosa'),
('Kevin Gonzalez', 'Vara de Tahuti perfeccionada'),
('Agustín Oliverio', 'Arco corto'),
('Martín Galeano', 'Arco Cargado'),
('Martín Galeano', 'Arco del Cazador'),
('Agustín Oliverio', 'Arco de Odiseo'),
('Nicolás Lopez', 'Arco de rama plateada'),
('Agustín Oliverio', 'Arco de Atalanta'),
('Agustín Oliverio', 'Esmeralda resplandeciente'),
('Martín Galeano', 'Talisman de Esmeralda'),
('Agustín Oliverio', 'Malla Esmeralda" 1250'),
('Agustín Oliverio', 'Piedra de Gea'),
('Agustina Gonzalez', 'Guantelete de Tebas'),
('Agustina Gonzalez', 'Malla de la renovación'),
('Martín Galeano', 'Coraza de cañonero'),
('Kevin Gonzalez', 'Katana'),
('Martín Galeano', 'Mil hojas dobladas'),
('Martín Galeano', 'Katana acelerada'),
('Agustina Gonzalez', 'Espada de oro'),
('Benjamín Castro Madrid', 'Filo serrado'),
('Agustín Oliverio', 'Bebedor de sombra'),
('Agustín Oliverio', 'Kusari Encantado'),
('Agustín Oliverio', 'Kusari Hechizado'),
('Agustín Oliverio', 'Guardia de Genji'),
('Damian Maldonado', 'Atuendo del Cazador Oni'),
('Agustín Oliverio', 'Kusari de Shogun'),
('Agustina Gonzalez', 'Piedra Druida'),
('Benjamín Castro Madrid', 'Piedra del Sabio'),
('Martín Galeano', 'Piedra de la Unión'),
('Agustín Oliverio', 'Furia del archidruida'),
('Agustín Oliverio', 'Piedra abisal'),
('Martín Galeano', 'Erosión'),
('Matheo Moro', 'Máscara del Luchador'),
('Benjamín Castro Madrid', 'Máscara de Rangda'),
('Agustín Oliverio', 'Gema del destino'),
('Martín Galeano', 'Borde afilado'),
('Benjamín Castro Madrid', 'Escudo de caballero'),
('Martín Galeano', 'Bastón del aprendiz'),
('Benjamín Castro Madrid', 'Pridwen'),
('Agustín Oliverio', 'Arondight'),
('Agustín Oliverio', 'Arco que no falla'),
('Agustina Gonzalez', 'Bastón de Merlín'),
('Agustina Gonzalez', 'Pridwen glorioso'),
('Kevin Gonzalez', 'Pridwen reverente'),
('Benjamín Castro Madrid', 'Bellota mágica'),
('Agustín Oliverio', 'Bellota vigorosa'),
('Agustina Gonzalez', 'Bellota de ortiga'),
('Agustín Oliverio', 'Bellota erizada'),
('Benjamín Castro Madrid', 'Bellota espinosa'),
('Agustín Oliverio', 'Bellota perenne'),
('Martín Galeano', 'Bellota carnosa'),
('Agustín Oliverio', 'Precio de la muerte'),
('Agustín Oliverio', 'Abrazo de la muerte'),
('Agustín Oliverio', 'Temperamento de la muerte'),
('Martín Galeano', 'Flecha dorada'),
('Nicolás Lopez', 'Flecha de diamante'),
('Agustín Oliverio', 'Flecha adornada'),
('Agustín Oliverio', 'Hacha del guerrero'),
('Kevin Gonzalez', 'Hacha desgarradora'),
('Matheo Moro', 'Hacha de animosidad'),
('Kevin Gonzalez', 'Cetro de maniquí'),
('Valentín Cañete', 'Maza de maniquí'),
('Nicolás Lopez', 'Espada oculta de maniquí'),
('Martín Galeano', 'Daga de Bumba'),
('Nicolás Lopez', 'Lanza de Bumba'),
('Ezequiel Fernandez', 'Martillo de Bumba'),
('Agustina Gonzalez', 'Arenas del tiempo'),
('Martín Galeano', 'Péndulo del tiempo'),
('Agustín Oliverio', 'Línea cronológica alternativa'),
('Agustín Oliverio', 'Manto vampírico'),
('Martín Galeano', 'Manto empapado de sangre'),
('Damian Maldonado', 'Manto de sacrificio'),
('Kevin Gonzalez', 'Regalo del centinela'),
('Valentín Cañete', 'Bendición del centinela'),
('Nicolás Lopez', 'Abrazo del centinela'),
('Agustín Oliverio', 'Benevolencia'),
('Agustín Oliverio', 'Compasión'),
('Benjamín Castro Madrid', 'Heroísmo'),
('Agustín Oliverio', 'Acero contaminado'),
('Damian Maldonado', 'Amuleto contaminado'),
('Nicolás Lopez', 'Peto contaminado'),
('Matheo Moro', 'Capucha de cuero'),
('Agustina Gonzalez', 'Capucha de cazador'),
('Kevin Gonzalez', 'Capucha de lider'),
('Agustina Gonzalez', 'Gema de conducto'),
('Martín Galeano', 'Gema de archimago'),
('Martín Galeano', 'Gema de concentración'),
('Benjamín Castro Madrid', 'Ojo de la Jungla'),
('Benjamín Castro Madrid', 'Vidente d ela Jungla'),
('Agustín Oliverio', 'Protector de la Juntgla'),
('Matheo Moro', 'Sello protector'),
('Benjamín Castro Madrid', 'Sello de la vieja guardia'),
('Martín Galeano', 'Sello infundido'),
('Martín Galeano', 'Máscara del protector'),
('Martín Galeano', 'Máscara de Lono'),
('Agustín Oliverio', 'Pendiente místico'),
('Matheo Moro', 'Pendientes relucientes'),
('Martín Galeano', 'Pendientes de espina de rosa'),
('Agustín Oliverio', 'Gemelos con joyas'),
('Agustín Oliverio', 'Aros bendecidos por hadas'),
('Agustín Oliverio', 'Adornos de esfinge'),
('Martín Galeano', 'Pinchos de la mantícora'),
('Nicolás Lopez', 'Pendientes de ala de grifo'),
('Benjamín Castro Madrid', 'Pendiente piedra azul'),
('Nicolás Lopez', 'Broche piedra azul'),
('Agustina Gonzalez', 'Piedra azul corrupta'),
('Kevin Gonzalez', 'Bandera de guerra'),
('Agustín Oliverio', 'Bandera espartana'),
('Agustín Oliverio', 'Estandarte de guerra'),
('Martín Galeano', 'Varita restaudadora'),
('Valentín Cañete', 'Vara de Curación'),
('Benjamín Castro Madrid', 'Vara de Asclepius'),
('Agustín Oliverio', 'Corazón rejuvenecedor'),
('Agustín Oliverio', 'Último suspiro'),
('Nicolás Lopez', 'Cetro bendito'),
('Benjamín Castro Madrid', 'Cetro espléndido'),
('Agustín Oliverio', 'Garrote caduceo'),
('Agustín Oliverio', 'Amplificador vital'),
('Agustina Gonzalez', 'Cetro de Sekhmet'),
('Agustín Oliverio', 'Grosellas grandiosas - Paso 1'),
('Agustín Oliverio', 'Grosellas grandiosas - Paso 2'),
('Ezequiel Fernandez', 'Grosellas grandiosas'),
('Kevin Gonzalez', 'Estofado energético - Paso 1'),
('Agustín Oliverio', 'Estofado energético - Paso 2'),
('Martín Galeano', 'Estofado energético'),
('Nicolás Lopez', 'Bao buenísimo - Paso 1'),
('Martín Galeano', 'Bao buenísimo - Paso 2'),
('Agustín Oliverio', 'Bap buenísimo'),
('Agustina Gonzalez', 'Vuelo magnífico - Paso 1'),
('Martín Galeano', 'Vuelo magnífico - Paso 2'),
('Agustín Oliverio', 'Vuelo magnífico'),
('Agustina Gonzalez', 'Ponche potente - Paso 1'),
('Benjamín Castro Madrid', 'Ponche potente - Paso 2'),
('Agustina Gonzalez', 'Ponche potente'),
('Benjamín Castro Madrid', 'Reliquia'),
('Agustín Oliverio', 'Amuleto Aegis'),
('Ezequiel Fernandez', 'Gran amuleto Aegis'),
('Damian Maldonado', 'Égida de juicio'),
('Agustín Oliverio', 'Égida de aceleración'),
('Martín Galeano', 'Cinturón de frenesí'),
('Agustina Gonzalez', 'Gran cinturón de frenesí'),
('Valentín Cañete', 'Cinturón del frenético'),
('Agustina Gonzalez', 'Cinturón del hambre insaciable'),
('Agustín Oliverio', 'Runa de pestañeo'),
('Agustín Oliverio', 'Gran runa de pestañeo'),
('Valentín Cañete', 'Runa de pestañeo abrasador'),
('Benjamín Castro Madrid', 'Runa de pestañeo corrupta'),
('Nicolás Lopez', 'Brazal de resplandor'),
('Damian Maldonado', 'Gran brazal de resplandor'),
('Agustín Oliverio', 'Brazal de iluminación'),
('Martín Galeano', 'Brazal de brillo'),
('Agustín Oliverio', 'Ankh maldito'),
('Agustín Oliverio', 'Gran ankh maldito'),
('Agustina Gonzalez', 'Ankh anemago'),
('Agustín Oliverio', 'Ankh maldito'),
('Agustín Oliverio', 'Alas celestiales'),
('Agustín Oliverio', 'Grandes alas celestiales'),
('Damian Maldonado', 'Alas de enredadera'),
('Agustina Gonzalez', 'Alas aceleradas'),
('Agustín Oliverio', 'Emblema horrorífico'),
('Nicolás Lopez', 'Gran emblema horrorífico'),
('Agustina Gonzalez', 'Emblema de pelibro creciente'),
('Benjamín Castro Madrid', 'Emblema de terror tembloroso'),
('Nicolás Lopez', 'Caparazón mágico'),
('Agustín Oliverio', 'Gran caparazón mágico'),
('Agustina Gonzalez', 'Caparazón fortificado'),
('Matheo Moro', 'Caparazón fantasma'),
('Agustín Oliverio', 'Capa de meditación'),
('Valentín Cañete', 'Gran capa de meditación'),
('Martín Galeano', 'Capa del avatar'),
('Martín Galeano', 'Capa del asceta'),
('Damian Maldonado', 'Cuencas de purificación'),
('Agustín Oliverio', 'Grandes cuencas de purificación'),
('Agustín Oliverio', 'Cuencas caóticas'),
('Nicolás Lopez', 'Cuencas temporales'),
('Agustina Gonzalez', 'Escudo de Espinas'),
('Agustina Gonzalez', 'Gran escudo de espinas'),
('Agustín Oliverio', 'Espinas de sobrecrecimiento'),
('Martín Galeano', 'Espinas de fuerza agotadora'),
('Martín Galeano', 'Lanza desgarradora'),
('Nicolás Lopez', 'Gran lanza desgarradora'),
('Nicolás Lopez', 'Explosión desgarradora'),
('Nicolás Lopez', 'Sifón desgarrador'),
('Matheo Moro', 'Fragmento de teletransporte'),
('Agustina Gonzalez', 'Gran fragmento teletransporte'),
('Nicolás Lopez', 'Teletransporte persistente'),
('Martín Galeano', 'Teletransporte heroico'),
('Kevin Gonzalez', 'Reliquia de fragmento'),
('Agustina Gonzalez', 'Fragmento de caparazón'),
('Agustina Gonzalez', 'Fragmento de visión'),
('Martín Galeano', 'Fragmento de cuerno'),
('Martín Galeano', 'Fragmento de garra'),
('Kevin Gonzalez', 'Fragmento de ala'),
('Nicolás Lopez', 'Posión curativa'),
('Agustín Oliverio', 'Posión de maná'),
('Agustín Oliverio', 'Centinela'),
('Martín Galeano', 'Elixir de poder'),
('Matheo Moro', 'Elixir de defensa'),
('Benjamín Castro Madrid', 'Fuarda centinela'),
('Agustina Gonzalez', 'Multi Poción'),
('Agustín Oliverio', 'Tácticas de Miedo'),
('Nicolás Lopez', 'Cáliz de curación'),
('Benjamín Castro Madrid', 'Cáliz de maná'),
('Agustina Gonzalez', 'Cáliz del Oráculo'),
('Martín Galeano', 'Poción del Barón'),
('Agustina Gonzalez', 'Pócima de poder'),
('Agustín Oliverio', 'Bomba rúnica');