insert into modo(modo, descripcion, cantJugadores)
values
	("Arena", "El modo de juego Arena es una batalla a muerte en donde tu objetivo es vencer a los jugadores enemigos y a sus súbditos reduciendo su contador de Tickets a cero. Cada equipo comienza con 500 tickets. Eliminar a un jugador enemigo resta 5 tickets de los enemigos. Eliminar a 10 jugadores enemigos hará aparecer el súbdito de asedio aliado. Eliminar un súbdito enemigo, resta 1 ticket de los enemigos. Ayudar a un súbdito a llegar al portal enemigo reduce 1 ticket de los enemigos. Ayudar al súbdito de asedio a alcanzar el portal enemigo reduce 10 tickets de los enemigos. El primer equipo en llegar a 0 tickets pierde.", 10),
	("Asalto", "La meta es ayudar a proteger tu base mientras atacas las defensas del enemigo. Una vez dejes tu fuente no podrás regresar hasta que hayas sido eliminado y reaparezcas. Para ganar, hay que destruir la Torre, el Fénix y el Titan del equipo enemigo. Por el mapa hay esferas que si las tocan funcionan como la reliquia de maná. Cada equipo es de 5 jugadores y los dioses se otorgan aleatoriamente.", 10),
	("Asedio", "En este modo de juego hay que adquirir colosos para presionar los carriles rápidamente y así poder destruir las torres enemigas, Fénix y Titan. Eliminar campamentos de la jungla y a Jugadores te da 5 Tickets. Eliminar un súbdito otorga 1 Ticket. 100 Tickets le otorgan a tu equipo un Coloso de Asedio. Eliminar el campamento de la jungla centrar otorga un coloso instantáneamente.", 8),
	("Clash", "Este modo tiene como característica un mapa de dos carriles con una pequeña jungla  hay un campamento en el centro. Tu base, defendida por dos torres, dos Fénix y un Titán, se ubica en un extremo. La base de tu enemigo se ubica al otro extremo del mapa.",10),
	("Conquista", "Este modo se caracteriza por ser un mapa de tres carriles rodeado por un área de jungla. Tu base es defendida por tres Fénix y un Titán, ubicados en un lado del mapa. La base de tu enemigo está al otro lado del mapa. Hay otros objetivos como campamentos neutrales de mejora o experiencia, demonio del Portal, gigante de Fuego y la Furia de Oro.", 10),
	("Justa", "Este modo se caracteriza por tener un solo carril en el mapa y una jungla lateral. Tu base es defendida por un Fénix y un Titán, ubicada en un lado del mapa. La base de tu enemigo está al otro lado del mapa. Para ganar, hay que destruir la Torre, el Fénix y el Titan del oponente.", 6);
	


