insert into panteon(panteon)
        values  ("Arturiano"),
                ("Babilónico"),
                ("Chino"),
                ("Celta"),
                ("Egipcio"),
                ("Griego"),
                ("Grandes Antiguos"),
                ("Hindú"),
                ("Japonés"),
                ("Maya"),
                ("Nórdico"),
                ("Polinesio"),
                ("Romano"),
                ("Eslavo"),
                ("Vudú"),
                ("Yoruba");